workflows:
  android-apk:
    name: Android APK
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
