workflows:
  simple-build:
    name: Simple APK Build
    environment:
      flutter: "3.16.0"
    scripts:
      - name: Build Debug APK
        script: |
          flutter pub get
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
